remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Vidit Gautam
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    github: samarsault
    linkedIn: in/viditg # format: locale/username
