remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  portfolio_image: ""

  name: Vidit Gautam
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    github: samarsault
    linkedIn: in/viditg # format: locale/username
  
  sitemap: true
  
  navigation:
    - title: "Project A"
      url: "/projectA"
    - title: "Project B"
      url: "/projectB"
